### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by shawark** [instaclustr/supportCenter#31]
`analysis/analyze.sh` preferred with default execution, `755` or else just for convenience.

Generated data file may contain sensitive information, might worth tightening permission not been global readable
```
drwxr-xr-x  4 shawxiao  staff     128 13 Aug 23:08 20200813T130755
-rw-r--r--  1 shawxiao  staff  134861 13 Aug 23:08 20200813T130755-data.zip
```

**Comment by imarsv** [comment]
Just read/write for owner
