### ISSUE TITLE
Indicative parameter check for command line 

### ISSUE THREAD

**Issue by shawark** [instaclustr/supportCenter#32]
Minor feature request

If minimum parameters are not provided by the command line or `yaml` file, running agent will always give the following output. 

```
./agent_darwin_amd64
INFO Instaclustr Agent
  -config string
    	The path to the configuration file
  -disable_known_hosts
    	Skip loading the user’s known-hosts file
  -l string
    	User to log in as on the remote machine
  -mc value
    	Metrics collecting hostname
  -mc-from string
    	Datetime (RFC3339 format, 2006-01-02T15:04:05Z07:00) to fetch metrics from some time point. (Default 1970-01-01 00:00:00 +0000 UTC)
  -mc-to string
    	Datetime (RFC3339 format, 2006-01-02T15:04:05Z07:00) to fetch metrics to some time point. (Default current datetime)
  -nc value
    	Node collecting hostnames
  -p int
    	Port to connect to on the remote host (default 22)
  -pk value
    	List of files from which the identification keys (private key) for public key authentication are read, in addition to default one (Default [HOME]/.ssh/id_rsa)
```

It is common in Linux. However, considering customers might not have enough knowledge/experience. They may struggle to find out what minimal parameters to run `agent`. It is not very obvious to find out which parameter `agent` has already got (could either from `yaml` or command line parameter) or which fields in `yaml` is optional (e.g. prometheus). Indicative outputs would be helpful, something like the following

```
./agent_darwin_amd64 -pk ~/.ssh/id_rsa
INFO Instaclustr Agent
[Required parameters to be provided]
  -l string
    	User to log in as on the remote machine

[Optional parameters to be provided]
  -disable_known_hosts
    	Skip loading the user’s known-hosts file
  -p int
    	Port to connect to on the remote host (default 22)
```

Although our TechOps team will be ready to assist, letting customers mock around to figure out most settings are would be still useful to minimize our labor costs and communication back and forth.

**Comment by benbromhead** [comment]
Closing
