### ISSUE TITLE
Collect more information

### ISSUE THREAD

**Issue by shawark** [instaclustr/supportCenter#33]
This is not completed yet. I just list the things I can think of worth collecting. I will try to add more in the following coming days.

* `ulimit -a` and currently opening files
* ...

**Comment by shawark** [comment]
- `free -m`
- `dmesg -T`
- System/kernel log `/var/log/message`

**Comment by slater-ben** [comment]
I think we will just add ulimit and free initially. dmesg and kernel log could be seen as grabbing more information than we need and put people offside.

**Comment by shawark** [comment]
It is tricky about kernel log but there are some very common issues

- Cassandra or other services are killed by the system OOM killer
- degraded underlying hardware (e.g. disk failure)

But yeah, we can ask when needed. It is just not obvious since we need to guess if the customer has OOM or disk failure

**Comment by benbromhead** [comment]
Complete in #33
