### ISSUE TITLE
The first node metrics are missed when more than one node is configured

### ISSUE THREAD

**Issue by shawark** [instaclustr/supportCenter#34]
https://github.com/instaclustr/supportCenter/blob/6809402339f6cfbe0cb6daca22b227a2ddf9825f/agent/main.go#L135-L140

The first node metrics are missed if more than one node is configured. TLDR the implication is for changing this bit. But comment out and the first node will be collected.

**Comment by imarsv** [comment]
We are processing only one metrics node, because "analysis" part works only with one prometheus database.

**Comment by shawark** [comment]
Right, I wonder why my `analyze.sh` is behaving strangely. This assumes port 9500 is open at the targets which might worth mentioned in the documentation.

**Comment by shawark** [comment]
sounds painful to manage the following when adding or removing nodes
```
  - job_name: 'self-monitoring-cassandra'
    static_configs:
      - targets: ['10.200.2.248:9500','10.200.2.99:9500','10.200.2.209:9500']
```

**Comment by shawark** [comment]
Also probably worth documenting this limitation in https://github.com/instaclustr/supportCenter/blob/master/docs/agent.md since it might confuse others too.

**Comment by imarsv** [comment]
> Right, I wonder why my `analyze.sh` is behaving strangely. This assumes port 9500 is open at the targets which might worth mentioned in the documentation.

Yes, it is strange. The `analyze.sh` starts docker compose with prometheus (9090), elasticsearch (9200), filebeat, grafana (3000). What targets do you mean?

**Comment by imarsv** [comment]
> Also probably worth documenting this limitation in https://github.com/instaclustr/supportCenter/blob/master/docs/agent.md since it might confuse others too.

`-mc HOST/IP - Metrics collecting hostname. E.g. the prometheus server.`

The agent collects metrics (makes prometheus database dump, all jobs), and collects logs from many cassandra nodes.

**Comment by shawark** [comment]
> > Right, I wonder why my `analyze.sh` is behaving strangely. This assumes port 9500 is open at the targets which might worth mentioned in the documentation.
> 
> Yes, it is strange. The `analyze.sh` starts docker compose with prometheus (9090), elasticsearch (9200), filebeat, grafana (3000). What targets do you mean?

I tried to gather metrics of 3 nodes. But when I load the metrics, prometheus graph just show all lines from one node. 
Nevermind I configured it wrongly, then it does not work

**Comment by shawark** [comment]
> > Also probably worth documenting this limitation in https://github.com/instaclustr/supportCenter/blob/master/docs/agent.md since it might confuse others too.
> 
> `-mc HOST/IP - Metrics collecting hostname. E.g. the prometheus server.`
> 
> The agent collect metrics (makes prometheus database dump, all jobs), and collects logs from many cassandra nodes.

I was not aware of I cannot put more than 1 server here, which is not very obvious.

**Comment by imarsv** [comment]
Only one Prometheus dump is supported. If we want to support multiple ones then we have to run multiple Prometheus in analyze.sh too but it was not in specification.

We can add this as the feature for next releases.

**Comment by shawark** [comment]
No worries. I am OK with one single server as long as I know what to do now.

One thing concerns me that
> sounds painful to manage the following on one node when adding or removing nodes 
> - job_name: 'self-monitoring-cassandra'
>    static_configs:
>      - targets: ['10.200.2.248:9500','10.200.2.99:9500','10.200.2.209:9500']


In practice, the customer may need puppet/chef or other tools (script) to regularly update `prometheus.yaml` the file of the server, the solution is not out of the box. As a result, the server will not collected all the metrics of all nodes as we expected. They may realize that and update the server `prometheus.yaml` file, but the history metrics were not collected.

**Comment by benbromhead** [comment]
Thanks for the feedback @shawark 

We probably need to clarify in the documentation that we just support a single prometheus server and prometheus should leverage its own service discovery mechanisms. 

@imarsv we can add multiple prometheus endpoints as a feature request to the list of issues, but I don't think its high priority right now.

If you want to see the service discovery mechanisms that prometheus supports, see https://prometheus.io/docs/prometheus/latest/configuration/configuration

It supports a huge range, and will likely plug into an existing SD mechanism the customer has.
