### ISSUE TITLE
Agent should have ability to generate example configs

### ISSUE THREAD

**Issue by B0073D** [instaclustr/supportCenter#36]
Agent should be able to generate example config files with a command line flag or detect that there are no configs and offer to generate them

**Comment by cmdrchkn** [comment]
argument handing is a little crunchy for this in 0.1.0- it still requires `-l <user>` to be specified even though it's just writing out an empty config file, if you try `./agent -generate-config ./test.yaml` it just barfs the usage message (which tells you `-l` is required, but it's not really relevant for generating the config)

**Comment by benbromhead** [comment]
Closing and recreating the comment as a standalone issue
