### ISSUE TITLE
Estimation about package size and download time

### ISSUE THREAD

**Issue by shawark** [instaclustr/supportCenter#39]
Also raised a similar concern in https://github.com/instaclustr/metricsAppliance/issues/5
Prometheus metrics can cause a very large package to download (depending on the number of nodes, period length requested). For example my test on a 3 nodes cluster for 2 weeks is about 2.5GB.

When running the supportcenter, the command output just show "Downloading snapshot...". The user has no clue how big the package is and how long to download it.
```
...
[2020-10-15T13:46:45+11:00]  INFO MC 3.128.132.94: Cleanup snapshot...
[2020-10-15T13:46:45+11:00]  INFO MC 3.128.132.94: Cleanup snapshot  OK
[2020-10-15T13:46:45+11:00]  INFO MC 3.128.132.94: Downloading snapshot...
[2020-10-15T13:47:06+11:00]  INFO MC 3.128.132.94: Downloading snapshot  OK
[2020-10-15T13:47:06+11:00]  INFO MC 3.128.132.94: Cleanup snapshot tarball...
...
```
This has consequent issues:
- connection might time out or the user cannot keep the terminal running long enough to download
- how to upload the package to us
- if the user terminate the download (e.g. CTRL+C), since cleanup snapshot tarball step is after the downloading. Then the tarball will not be removed from the server

**Comment by imarsv** [comment]
The package size and downloading remaining implemented.
Moving cleanup issues in to separate ticket #41

**Comment by benbromhead** [comment]
Closing out issue -> Follow up in #41
