### ISSUE TITLE
Running Agent on Windows swaps slashes & can't grab config files

### ISSUE THREAD

**Issue by cmdrchkn** [instaclustr/supportCenter#46]
In the current release (v0.1.0), the paths from settings.yml get the slashes swapped from `/` to the local path separator '\', which breaks the sftp transfer since the modified path doesn't exist on the remote host.

I've submitted a PR (https://github.com/instaclustr/supportCenter/pull/45) that should resolve this

**Comment by jordanbraiuka** [comment]
This pull request has been merged
